### ISSUE TITLE
请问要怎么入门计算机安全？

### ISSUE THREAD

**Issue by superstarboy** [No-Github/1earn#1]

**Comment by No-Github** [comment]
想快速入门，只需要去学习如何操作，但想要走的更远，就必须去学习理论和基础

捷径是有的，但不是适合于每个人

我建议先从各类靶机环境开始练习，先体会一下攻击的手段，然后去了解背后的原理以及漏洞出现的原因，这比听那些卖课/卖教程的吹逼会有效率
