### ISSUE TITLE
readme 这里是不是错了？

### ISSUE THREAD

**Issue by mfslog** [No-Github/1earn#3]
**完**  事开头难,然后一直开头一直难..._   ==> **万** 事开头难

**Comment by No-Github** [comment]
尴尬了😅，一直没注意这个，谢谢提醒

**Comment by willson-chen** [comment]
@JerryZhou343 你好，我是getty社区的，可否查看一下您的jerry.chau@qq.com的邮箱，我向您邮箱发送了消息。有些事需要与您协商
