### ISSUE TITLE
大神能否添加一些入门的、系统的文档

### ISSUE THREAD

**Issue by lydiary** [No-Github/1earn#4]

**Comment by No-Github** [comment]
好的，我找个时间做一个学习线路图，和相应的笔记对应起来，这样阅读体验应该会好一些😊

**Comment by lydiary** [comment]
> 好的，我找个时间做一个学习线路图，和相应的笔记对应起来，这样阅读体验应该会好一些😊

太棒了，大大的赞~

**Comment by No-Github** [comment]
做了一个基础的 [roadmap 笔记](https://github.com/No-Github/1earn/blob/master/roadmap.md),后续也会不断完善,有其他需求或问题欢迎在 issue 提出
